name: 'Xamarin.iOS Signed Build'
description: 'Build and Sign Xamarin.iOS Project'
inputs:
  csproj_path:
    description: 'Path to csproj file'
    required: true
  mobileprovision:
    description: 'Base64 representation of your mobile provisioning file'
    required: true
  cert_p12:
    description: 'Base64 representation p12 distribution cert'
    required: true
  p12_pass:
    description: 'Password used when exporting p12 distribution cert from keychain'
    required: true
  configuration:
    description: 'Build configuration'
    required: false
    default: 'Release'
  mono_version:
    description: 'Version of mono to use for build'
    required: false
    default: 'stable'
  xamarin_ios_version:
    description: 'Version of Xamarin.iOS to use for build'
    required: false
    default: 'stable'
runs:
  using: "composite"
  steps:
    - run: ${{ github.action_path }}/build-ios.sh
      env:
          CSPROJ_PATH: ${{ inputs.csproj_path }}
          MOBILEPROVISION: ${{ inputs.mobileprovision }}
          CERT_P12: ${{ inputs.cert_p12 }}
          P12_PASS: ${{ inputs.p12_pass }}
          CONFIGURATION: ${{ inputs.configuration }}
          MONO_VERSION: ${{ inputs.mono_version }}
          XAMARIN_IOS_VERSION: ${{ inputs.xamarin_ios_version }}
      shell: bash
